version: "2"
services:
  search:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - hk-mongodb
  hk-mongodb:
    image: mongo:3.6
    container_name: "hk-mongodb"
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="user"
      - MONGODB_USER="pass"
