version: "2"
services:
  search:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - db
  db:
    image: mongo
    container_name: mongodb
    ports:
    - "27017:27017"
    volumes:
    - ./data/db:/data/db
